/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecruitRouteImport } from './routes/recruit'
import { Route as AssessIndexRouteImport } from './routes/assess.index'
import { Route as AssessSkillIdRouteImport } from './routes/assess.$skillId'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitRoute = RecruitRouteImport.update({
  id: '/recruit',
  path: '/recruit',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessIndexRoute = AssessIndexRouteImport.update({
  id: '/assess/',
  path: '/assess/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessSkillIdRoute = AssessSkillIdRouteImport.update({
  id: '/assess/$skillId',
  path: '/assess/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/recruit': typeof RecruitRoute
  '/assess/$skillId': typeof AssessSkillIdRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/assess/': typeof AssessIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/recruit': typeof RecruitRoute
  '/assess/$skillId': typeof AssessSkillIdRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/assess': typeof AssessIndexRoute
  '/learn': typeof LearnIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/recruit': typeof RecruitRoute
  '/assess/$skillId': typeof AssessSkillIdRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/assess/': typeof AssessIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/applications'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/portfolio'
    | '/profile'
    | '/recruit'
    | '/assess/$skillId'
    | '/learn/$slug'
    | '/opportunities/$id'
    | '/assess/'
    | '/learn/'
    | '/opportunities/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/applications'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/portfolio'
    | '/profile'
    | '/recruit'
    | '/assess/$skillId'
    | '/learn/$slug'
    | '/opportunities/$id'
    | '/assess'
    | '/learn'
    | '/opportunities'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/applications'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/portfolio'
    | '/profile'
    | '/recruit'
    | '/assess/$skillId'
    | '/learn/$slug'
    | '/opportunities/$id'
    | '/assess/'
    | '/learn/'
    | '/opportunities/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApplicationsRoute: typeof ApplicationsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRoute
  RecruitRoute: typeof RecruitRoute
  AssessSkillIdRoute: typeof AssessSkillIdRoute
  LearnSlugRoute: typeof LearnSlugRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  AssessIndexRoute: typeof AssessIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruit': {
      id: '/recruit'
      path: '/recruit'
      fullPath: '/recruit'
      preLoaderRoute: typeof RecruitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/': {
      id: '/assess/'
      path: '/assess'
      fullPath: '/assess/'
      preLoaderRoute: typeof AssessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/$skillId': {
      id: '/assess/$skillId'
      path: '/assess/$skillId'
      fullPath: '/assess/$skillId'
      preLoaderRoute: typeof AssessSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApplicationsRoute: ApplicationsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  RecruitRoute: RecruitRoute,
  AssessSkillIdRoute: AssessSkillIdRoute,
  LearnSlugRoute: LearnSlugRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  AssessIndexRoute: AssessIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
